Neos:
  Flow:
    http:
      middlewares:
        'crossContentRepositoryReferencePreview':
          position: 'after detectSite'
          middleware: 'Shel\Neos\CrossContentRepositoryReferences\Middleware\CrossContentRepositoryPreviewMiddleware'
